# Generated by Django 3.1.7 on 2021-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_facebookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usid', models.CharField(max_length=10000)),
                ('adcount', models.CharField(max_length=500)),
            ],
        ),
    ]
