# Generated by Django 3.1.7 on 2021-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iad', models.CharField(max_length=11000)),
                ('cash', models.CharField(max_length=1000)),
            ],
        ),
    ]
